name: Publish to GitHub Release

on:
  push:
    tags:
      - 'V*'
      - 'MG-V*'
  workflow_dispatch:
    inputs:
        tag:
          description: 'Release tag (e.g. v1.2.3)'
          required: true

permissions:
  contents: write
  packages: write

jobs:
  publish-main:
    if: ${{ (github.event_name == 'push' && startsWith(github.ref_name, 'V')) || (github.event_name == 'workflow_dispatch' && startsWith(inputs.tag, 'V')) }}
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: build
        run: dotnet publish NeuroSDKCsharp/NeuroSDKCsharp.csproj -c Release -o out

      - name: public release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create $RELEASE_TAG out/NeuroSDKCsharp.dll
  publish-mono-game:
    if: ${{ (github.event_name == 'push' && startsWith(github.ref_name, 'MG-V')) || (github.event_name == 'workflow_dispatch' && startsWith(inputs.tag, 'MG-V')) }}
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: checkout
        run: git checkout $RELEASE_TAG

      - name: build
        run: dotnet publish NeuroSDKCsharp/NeuroSDKCsharp.csproj -c Release -o out

      - name: public release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create $RELEASE_TAG out/NeuroSDKCsharp.dll